### ISSUE TITLE
Encryption with BindKey?

### ISSUE THREAD

**Issue by nagyrobi** [stumpylog/bthome-weather-station#1]
It would be very useful to add a security layer by encrypting the packets with a BindKey (just like pvvx firmware can do it, sends BTHome broadcasts encrypted) - HA will automatically ask for the key when adding the device to it.

**Comment by stumpylog** [comment]
Is this different from the BTHome encryption?  That one is in the todo list.

**Comment by nagyrobi** [comment]
Not quite sure, but if it has it's own, even better.

**Comment by nagyrobi** [comment]
Does it support some kind of rolling key mechanism?
Eg. when sending an event or the same value repeatedly via BTHome, will the ecryption result in the same data? If yes, then it needs some extra random stuff added else it can be spoofed... (eg. a random number sensor).

**Comment by stumpylog** [comment]
The documentation on it is pretty scarce: https://bthome.io/#encryption

But from the [example script](https://github.com/Bluetooth-Devices/bthome-ble/blob/main/src/bthome_ble/bthome_encryption.py#L62) I don't think that would be the case, mostly since there is a count included as part of the nonce.  But I am far from a security expert.

**Comment by Ernst79** [comment]
We have expanded the Encryption section on the bthome.io page and have created a dedicated page now.

https://bthome.io/encryption/

BTHome supports [AES encryption (CCM mode)](https://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.nrf52832.ps.v1.1%2Fccm.html) and has a counter which should be changed (increased) each advertisement. I still need to build in this check for an increase in the counter, but it is planned for the near future.

**Comment by stumpylog** [comment]
Wow, didn't notice a v2 was released.  Regarding encryption, why is the `cipher.update(b"\x11")` done?  It feels strange to see what looks like a magic number being used.

**Comment by Ernst79** [comment]
It is released, but HA 2022.12 is not released yet. So you have to wait 3 weeks, or use a dev environment of Home Assistant. 

Not sure why this cipher.update is used, I didn't made this encryption myself. I think it is taken over from the Xiaomi encryption, where they do the same. 

In this example, I see something similar. It looks like it is used for a header, to remain in the clear. 

https://pycryptodome.readthedocs.io/en/latest/src/cipher/modern.html?highlight=update()#ccm-mode
https://legrandin.github.io/pycryptodome/Doc/3.4.6/Crypto.Cipher.AES-module.html

I'm not sure what happens if we leave it out. Probably not much, but if we change it, it will affect all current implementations, I'm afraid.

**Comment by Ernst79** [comment]
This is what the docs say

<html>
<body>
<dt id="update" style="box-sizing: border-box; font-weight: 700; margin: 0px 0px 6px; display: table; font-size: 14.4px; line-height: normal; background: rgb(231, 242, 250); color: rgb(41, 128, 185); border-top: 3px solid rgb(106, 176, 222); padding: 6px; position: relative; font-family: Lato, proxima-nova, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code class="descname" style="box-sizing: border-box; font-family: SFMono-Regular, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, Courier, monospace; font-size: 14.4px; white-space: nowrap; max-width: 100%; background: transparent; border: none; padding: 0px; color: rgb(0, 0, 0); overflow-x: auto; font-weight: 700;">update</code><span class="sig-paren" style="box-sizing: border-box;">(</span><em style="box-sizing: border-box;">data</em><span class="sig-paren" style="box-sizing: border-box;">)</span><a class="headerlink" href="https://pycryptodome.readthedocs.io/en/latest/src/cipher/modern.html#update" title="Permalink to this definition" style="box-sizing: border-box; color: rgb(64, 64, 64); text-decoration: none; cursor: pointer; display: inline-block; font: 14.4px / 1 FontAwesome; text-rendering: auto; -webkit-font-smoothing: antialiased; opacity: 0; margin-left: 0.5em;">¶</a></dt><dd style="box-sizing: border-box; margin: 0px 0px 12px 24px; line-height: 24px; color: rgb(64, 64, 64); font-family: Lato, proxima-nova, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(252, 252, 252); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="box-sizing: border-box; line-height: 24px; font-size: 16px; margin: 0px 0px 12px;">Authenticate those parts of the message that get delivered as is, without any encryption (like headers). It is similar to the<span> </span><code class="docutils literal notranslate" style="box-sizing: border-box; font-family: SFMono-Regular, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, Courier, monospace; font-size: 12px; white-space: normal; max-width: 100%; background: rgb(255, 255, 255); border: 1px solid rgb(225, 228, 229); padding: 2px 5px; color: rgb(231, 76, 60); overflow-x: auto;"><span class="pre" style="box-sizing: border-box;">update()</span></code><span> </span>method of a MAC object. Note that all data passed to<span> </span><code class="docutils literal notranslate" style="box-sizing: border-box; font-family: SFMono-Regular, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, Courier, monospace; font-size: 12px; white-space: normal; max-width: 100%; background: rgb(255, 255, 255); border: 1px solid rgb(225, 228, 229); padding: 2px 5px; color: rgb(231, 76, 60); overflow-x: auto;"><span class="pre" style="box-sizing: border-box;">encrypt()</span></code><span> </span>and<span> </span><code class="docutils literal notranslate" style="box-sizing: border-box; font-family: SFMono-Regular, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, Courier, monospace; font-size: 12px; white-space: normal; max-width: 100%; background: rgb(255, 255, 255); border: 1px solid rgb(225, 228, 229); padding: 2px 5px; color: rgb(231, 76, 60); overflow-x: auto;"><span class="pre" style="box-sizing: border-box;">decrypt()</span></code><span> </span>get automatically authenticated already.</p>

Parameters: | data (bytes) – the extra data to authenticate
-- | --


</dd>
</body>
</html>update(data)[¶](https://pycryptodome.readthedocs.io/en/latest/src/cipher/modern.html#update)
Authenticate those parts of the message that get delivered as is, without any encryption (like headers). It is similar to the update() method of a MAC object. Note that all data passed to encrypt() and decrypt() get automatically authenticated already.

Parameters:	data (bytes) – the extra data to authenticate

**Comment by stumpylog** [comment]
With the update to the v2 format, I've made good progress on getting something workable for encryption.

With the addition of 8 bytes to the payload (counter and MIC), it does restrict the amount of sensor data and length of the name, but it's a necessary tradeoff.

**Comment by Ernst79** [comment]
BTW. The `cipher.update(b"\x11")` is removed in V2

**Comment by junchao98** [comment]
maybe not require reverse engineering the Python and replicating it to that library.
just use **mbedtls_ccm_encrypt_and_tag**.
 param iv  The initialization vector (nonce)
 param tag       The buffer holding the authentication field(digest)

by the way, we should use #include "mbedtls/ccm.h"

**Comment by junchao98** [comment]
I have implemented this feature  https://github.com/stumpylog/bthome-weather-station/pull/3

**Comment by stumpylog** [comment]
Thanks to @junchao98 encryption can now be configured.  I've added a bit to the readme on it as well.
